apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: next-js-
spec:
  serviceAccountName: build-bot
  params:
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/emea-8-nextjs-app-linjing-tomasz.git
    - name: image-repo
      value: quay.io/fu_linjing/next-app
    - name: app-name
      value: express-sample-app
  pipelineRef:
    name: image-build-pipeline
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce
