apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/tektoncd/catalog/main/task/npm/0.1/npm.yaml
- build-bot.ServiceAccount.yaml
- create-configuration.yaml
- deploy.Task.yaml
- nextjs.pipeline.yaml
- git-credentials.secret.yaml
- production-repository.ConfigMap.yaml
- quay-io-credentials.secret.yaml
- save-configuration.yaml
- webhook-trigger.EventListener.yaml
